- platform: mqtt
  name: "humidifier_01_state_on_off"
  state_topic: "danilov_smart_devices/humidifier_01/sensor/enable_state"
  command_topic: "danilov_smart_devices/humidifier_01/switch/state"
  payload_on: "2"
  payload_off: "0"
  state_on: "2"
  state_off: "0"
  value_template: >
    {% if value == "1" or value == "2" %}
      2
    {% else %}
      0
    {% endif %}
  availability:
    - topic: "danilov_smart_devices/humidifier_01/sensor/water"
      payload_available: "1"
      payload_not_available: "0"

- platform: mqtt
  name: "humidifier_01_state_low_high"
  state_topic: "danilov_smart_devices/humidifier_01/sensor/enable_state"
  command_topic: "danilov_smart_devices/humidifier_01/switch/state"
  payload_on: "2"
  payload_off: "1"
  state_on: "2"
  state_off: "1"
  value_template: >
    {% if value == "0" or value == "1" %}
      1
    {% else %}
      2
    {% endif %}
  availability:
    - topic: "danilov_smart_devices/humidifier_01/sensor/water"
      payload_available: "1"
      payload_not_available: "0"
