- platform: polling
  api_key: !secret telegram_danilov_main_ha_bot_secret_key
  allowed_chat_ids:
    - !secret telegram_danilov_info_group_id
    - !secret telegram_danilov_0x33_user_id
    - !secret telegram_ann15294_user_id
