- id: '1646322477698'
  alias: Включение света в зале с кнопки
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: 7f0620b7401ecbec478682e25777e2f3
    type: action
    subtype: single
    discovery_id: 0x00158d000276ea3b action_single
  condition: []
  action:
  - type: toggle
    device_id: 8607f978a429dda7c189a7c71ffe637b
    entity_id: light.yeelight_arwen_550c
    domain: light
  mode: single
- id: '1646322573266'
  alias: Включение ночной подсветки в зале
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: 7f0620b7401ecbec478682e25777e2f3
    type: action
    subtype: double
    discovery_id: 0x00158d000276ea3b action_double
  condition: []
  action:
  - type: turn_off
    device_id: 8607f978a429dda7c189a7c71ffe637b
    entity_id: light.yeelight_arwen_550c
    domain: light
  - type: turn_on
    device_id: 8607f978a429dda7c189a7c71ffe637b
    entity_id: light.yeelight_arwen_550c_ambilight
    domain: light
    brightness_pct: 30
  mode: single
