homeassistant:
  # Name of the location where Home Assistant is running
  name: Danilov Home Assistant
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude_coord
  longitude: !secret longitude_coord
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Moscow

  # allowlist_external_dirs:
  #   - /config

  # customize: !include_dir_merge_named includes/entities/customizations
  packages: !include_dir_merge_named includes/packages

# Configurations
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - 192.168.3.3
lovelace: !include integrations/lovelace.yaml
frontend: !include integrations/frontend.yaml
recorder: !include integrations/recorder.yaml
history: ~ #!include integrations/history.yaml
logbook: ~ #!include integrations/logbook.yaml
#map: ~
media_source: ~
mobile_app: ~
person: ~
ssdp: ~
stream: ~
# sun: ~
system_health: ~
tag: ~
#updater: ~
zone: ~
cloud: ~
# energy: ~
ffmpeg: ~

# Integrations
#hacs: !include integrations/hacs.yaml
influxdb: !include integrations/influxdb.yaml
telegram_bot: !include integrations/telegram_bot.yaml
yandex_smart_home: !include integrations/yandex_smart_home.yaml
yandex_station_intents: !include integrations/yandex_station_intents.yaml
downloader:
  download_dir: www/downloads
# automation: !include automations.yaml
# automation split: !include_dir_merge_list includes/automations
# script: !include_dir_merge_named includes/scripts

# Entities
# sensor: !include_dir_merge_list includes/entities/sensors
# binary_sensor: !include_dir_merge_list includes/entities/binary_sensors
# switch: !include_dir_merge_list includes/entities/switches
# remote: !include_dir_merge_list includes/entities/remotes
# notify: !include_dir_merge_list includes/entities/notifies
# timer: !include_dir_merge_list includes/entities/timers
# input_boolean: !include_dir_merge_list includes/entities/input_booleans
# input_number: !include_dir_merge_named includes/entities/input_numbers
# input_button: !include_dir_merge_named includes/entities/input_buttons
# vacuum: !include_dir_merge_list includes/entities/vacuums
# camera: !include_dir_merge_list includes/entities/cameras
#media_player:
#device_tracker: !include_dir_merge_list includes/entities/device_trackers
#fan: !include_dir_merge_list includes/entities/fans
