blueprint:
  name: Автоматический контроль света
  domain: automation
  input:
    motion_sensor:
      name: Датчики движения (*)
      selector:
        entity:
          domain: binary_sensor
          multiple: true

    door_sensors:
      name: Датчики открытия двери
      default: []
      selector:
        entity:
          domain: binary_sensor
          multiple: true

    manual_light_switch:
      name: Ручной переключатель света (*)
      selector:
        entity:
          multiple: true
          domain:
            - switch
            - input_boolean
    manual_light_script_on:
      name: Скрипт ручного включния света
      default: []
      selector:
        entity:
          multiple: true
          domain: script
    manual_light_script_off:
      name: Скрипт ручного выключния света
      default: []
      selector:
        entity:
          multiple: true
          domain: script
    manual_time_delay:
      name: Время работы включенного света по ручному включению
      default: 30
      selector:
        number:
          min: 0
          max: 1440
          step: 0.5
          unit_of_measurement: minutes

    main_light:
      name: Свет (*)
      selector:
        entity:
          multiple: true
          domain: light
    main_light_script_on:
      name: Скрипт включния света
      default: []
      selector:
        entity:
          multiple: true
          domain: script
    main_light_script_off:
      name: Скрипт выключния света
      default: []
      selector:
        entity:
          multiple: true
          domain: script
    main_time_delay:
      name: Время работы включенного света по триггеру без движения
      default: 2
      selector:
        number:
          min: 0
          max: 30
          step: 0.5
          unit_of_measurement: minutes

    night_light_enabled:
      name: Включить работу с ночным светом
      default: "off"
      selector:
        select:
          options:
            - label: Включить
              value: "on"
            - label: Выключить
              value: "off"
    night_light:
      name: Ночной свет
      default: []
      selector:
        entity:
          multiple: true
          domain: light
    night_light_script_on:
      name: Скрипт включния ночного света
      default: []
      selector:
        entity:
          multiple: true
          domain: script
    night_light_script_off:
      name: Скрипт выключния ночного света
      default: []
      selector:
        entity:
          multiple: true
          domain: script
    night_time_delay:
      name: Время работы включенного света по триггеру ночью без движения
      default: 1
      selector:
        number:
          min: 0
          max: 30
          step: 0.5
          unit_of_measurement: minutes
    night_lights_after_time:
      name: Начало ночного времени
      default: "23:00:00"
      selector:
        time:
    night_lights_before_time:
      name: Конец ночного времени
      default: "08:00:00"
      selector:
        time:

mode: restart

variables:
  motion_sensor: !input motion_sensor
  door_sensors: !input door_sensors
  manual_light_switch: !input manual_light_switch
  manual_time_delay: !input manual_time_delay
  manual_light_script_on: !input manual_light_script_on
  manual_light_script_off: !input manual_light_script_off

  main_light: !input main_light
  main_light_script_on: !input main_light_script_on
  main_light_script_off: !input main_light_script_off
  main_time_delay: !input main_time_delay

  night_light_enabled: !input night_light_enabled
  night_light: !input night_light
  night_light_script_on: !input night_light_script_on
  night_light_script_off: !input night_light_script_off
  night_time_delay: !input night_time_delay
  night_lights_after_time: !input night_lights_after_time
  night_lights_before_time: !input night_lights_before_time

trigger:
  - platform: state
    id: "motion_sensor_on_trigger"
    entity_id: !input motion_sensor
    from: "off"
    to: "on"
  - platform: state
    id: "on_manual_light_switch_trigger"
    entity_id: !input manual_light_switch
    from: "off"
    to: "on"
  - platform: state
    id: "off_manual_light_switch_trigger"
    entity_id: !input manual_light_switch
    from: "on"
    to: "off"
  - platform: state
    id: "open_door_trigger"
    entity_id: !input door_sensors
    from: "off"
    to: "on"

action:
  - choose:
      - alias: "Ручное включение основного света"
        conditions:
          - condition: trigger
            id: "on_manual_light_switch_trigger"
        sequence:
          - alias: "Включение основного света"
            service: script.turn_on
            target:
              entity_id:
                - !input manual_light_script_on
          - delay:
              minutes: !input manual_time_delay
          - alias: "Выключить ручное включение после делея"
            service: switch.turn_off
            target:
              entity_id:
                - !input manual_light_switch

      - alias: "Ручное выключение основного света (после отсутствия движения)"
        conditions:
          - condition: state
            entity_id: !input motion_sensor
            match: any
            state: "on"
          - condition: state
            entity_id: !input manual_light_switch
            state: "on"
        sequence:
          - wait_for_trigger:
              - platform: state
                entity_id: !input motion_sensor
                from: "on"
                to: "off"
          - delay:
              minutes: !input manual_time_delay
          - alias: "Выключить ручное включение после делея"
            service: switch.turn_off
            target:
              entity_id:
                - !input manual_light_switch

      - alias: "Ручное выключение основного света"
        conditions:
          - condition: trigger
            id: "off_manual_light_switch_trigger"
        sequence:
          - if:
              - "{{ night_light_enabled == 'on' }}"
            then:
              - alias: "Выключение ночного света"
                service: script.turn_on
                target:
                  entity_id:
                    - !input night_light_script_off
          - alias: "Выключение основного света"
            service: script.turn_on
            target:
              entity_id:
                - !input manual_light_script_off

      - alias: "Включение света после открытия двери"
        conditions:
          - condition: trigger
            id: "open_door_trigger"
          - condition: state
            entity_id: !input manual_light_switch
            state: "off"
        sequence:
          - if:
              - "{{ night_light_enabled == 'on' }}"
              - condition: time
                after: !input night_lights_after_time
                before: !input night_lights_before_time
            then:
              - alias: "Включение ночного света"
                service: script.turn_on
                target:
                  entity_id:
                    - !input night_light_script_on
              - delay:
                  minutes: !input main_time_delay
              - service: script.turn_on
                target:
                  entity_id:
                    - !input night_light_script_off
            else:
              - alias: "Включение основного света"
                service: script.turn_on
                target:
                  entity_id:
                    - !input main_light_script_on
              - delay:
                  minutes: !input main_time_delay
              - service: script.turn_on
                target:
                  entity_id:
                    - !input main_light_script_off

      - alias: "Включение ночного света"
        conditions:
          - "{{ night_light_enabled == 'on' }}"
          - condition: time
            after: !input night_lights_after_time
            before: !input night_lights_before_time
          - condition: state
            entity_id: !input manual_light_switch
            state: "off"
        sequence:
          - alias: "1. Включение ночного света"
            service: script.turn_on
            target:
              entity_id:
                - !input night_light_script_on

          - alias: "2. Ожидание выключения сенсора"
            wait_for_trigger:
              - platform: state
                entity_id: !input motion_sensor
                from: "on"
                to: "off"
              - platform: state
                entity_id: !input manual_light_switch

          - if:
              - condition: state
                entity_id: !input manual_light_switch
                state: "off"
            then:
              - alias: "3. Ожидание делея выключения или ручного переключения"
                wait_for_trigger:
                  - platform: state
                    entity_id: !input motion_sensor
                    from: "off"
                    to: "on"
                  - platform: state
                    entity_id: !input manual_light_switch
                timeout:
                  minutes: !input night_time_delay
              - if:
                  - condition: state
                    entity_id: !input motion_sensor
                    match: all
                    state: "off"
                  - condition: state
                    entity_id: !input manual_light_switch
                    state: "off"
                then:
                  - alias: "Выключение ночного света"
                    service: script.turn_on
                    target:
                      entity_id:
                        - !input night_light_script_off

      - alias: "Включение основного света"
        conditions:
          - condition: state
            entity_id: !input manual_light_switch
            state: "off"
        sequence:
          - alias: "1. Включение света"
            service: script.turn_on
            target:
              entity_id:
                - !input main_light_script_on

          - alias: "2. Ожидание выключения сенсора"
            wait_for_trigger:
              - platform: state
                entity_id: !input motion_sensor
                from: "on"
                to: "off"
              - platform: state
                entity_id: !input manual_light_switch
                from: "on"
                to: "off"

          - if:
              - condition: state
                entity_id: !input manual_light_switch
                state: "off"
            then:
              - alias: "3. Ожидание делея выключения или ручного переключения"
                wait_for_trigger:
                  - platform: state
                    entity_id: !input motion_sensor
                    from: "off"
                    to: "on"
                  - platform: state
                    entity_id: !input manual_light_switch
                timeout:
                  minutes: !input main_time_delay
              - if:
                  - condition: state
                    entity_id: !input motion_sensor
                    match: all
                    state: "off"
                  - condition: state
                    entity_id: !input manual_light_switch
                    state: "off"
                then:
                  - alias: "Выключение света"
                    service: script.turn_on
                    target:
                      entity_id:
                        - !input main_light_script_off
